#!/bin/bash

. /sbin/sabayondocker-functions.sh

safety_check $SABAYON_DOCKER_IMAGE

export SABAYON_DOCKER_IMAGE

# Running default

SABAYON_DOCKER_OPTIONS=(
	"-v $SABAYON_HOME/certs/:/root/.ssh/"
	"-v $SABAYON_HOME/distfiles:/usr/portage/distfiles"
	"-v $SABAYON_HOME/confs/entropy/:/etc/entropy/"
	"-v $SABAYON_HOME/confs/distcc_hosts:/etc/distcc/hosts"
	"-v $SABAYON_HOME/keys/:/etc/entropy/gpg-keys/"
	"-v $SABAYON_HOME/artifacts:/usr/portage/packages"
	"-e FEATURES -e DISTCC_SSH -e DISTCC_HOSTS -e MAKEOPTS -e SSH_AUTH_SOCK"
	"--cap-add=SYS_PTRACE"
)

export SABAYON_CPUS
export SABAYON_MEMORY_RESERVATION
export SABAYON_MEMORY_SWAP
export SABAYON_MEMORY
export SABAYON_HOME
export SABAYON_DOCKER_OPTIONS
export SABAYON_COMMAND


echo
echo "----> Printing image history, hang tight"
echo

echo "*****************************************"
docker history $SABAYON_DOCKER_IMAGE || exit 0
echo "*****************************************"



spawn_container ${SABAYON_DOCKER_OPTIONS[@]}
