#!/bin/bash

# Running default
SABAYON_CPUS="${SABAYON_CPUS:-3}"
SABAYON_MEMORY_RESERVATION="${SABAYON_MEMORY_RESERVATION:-50M}"
SABAYON_MEMORY_SWAP="${SABAYON_MEMORY_SWAP:-710M}"
SABAYON_MEMORY="${SABAYON_MEMORY:-100M}"
SABAYON_DOCKER_IMAGE_PLAYGROUND="playground"


SABAYON_DOCKER_OPTIONS=(
	"-v $SABAYON_HOME/distfiles:/usr/portage/distfiles"
	"-v $SABAYON_HOME/confs/entropy_arm.conf:/etc/entropy/repositories.conf.d/entropy_arm.conf"
	"-v $SABAYON_HOME/confs/distcc_hosts:/etc/distcc/hosts"
	"-v $SABAYON_HOME/artifacts:/usr/portage/packages"
	"--rm -e FEATURES -e DISTCC_SSH -e DISTCC_HOSTS -e MAKEOPTS -e SSH_AUTH_SOCK"
)

export SABAYON_CPUS
export SABAYON_MEMORY_RESERVATION
export SABAYON_MEMORY_SWAP
export SABAYON_MEMORY
export SABAYON_HOME
export SABAYON_DOCKER_OPTIONS
export SABAYON_COMMAND

. /sbin/sabayondocker-functions.sh

docker tag -f ${SABAYON_DOCKER_IMAGE} ${SABAYON_DOCKER_IMAGE_PLAYGROUND}

SABAYON_DOCKER_IMAGE="${SABAYON_DOCKER_IMAGE_PLAYGROUND}"
export SABAYON_DOCKER_IMAGE

spawn_container ${SABAYON_DOCKER_OPTIONS[@]}
